---
version: "2.4"

networks:
  internal:
    name: ${NETWORK_NAME}

volumes:
  registry-auth: {}
  registry-data: {}

services:
  ingress:
    image: traefik:v2.3
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  deployer:
    image: golang:1.15-alpine
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app
    command: ["go", "run", "./cmd/deployer/main.go", "${NETWORK_NAME}"]
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  registry:
    image: registry:2.7
    volumes:
      - registry-auth:/var/lib/registry
      - registry-data:/auth
      - ./config/registry.yml:/etc/docker/registry/config.yml
    labels:
      - "traefik.http.routers.registry.rule=Host(`${AUTOSRV_HOSTNAME}`)"
      - "traefik.docker.network=${NETWORK_NAME}"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.http.services.registry.loadbalancer.passhostheader=true"
    networks:
      - internal
