---
version: "2.4"

networks:
  internal:
    name: ${NETWORK_NAME}

volumes:
  registry-data: {}

services:
  ingress:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

  deployer:
    networks:
      - internal

  registry:
    networks:
      - internal
